services:
  web:
    build: .
    container_name: shopee_web
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./logs:/app/logs
      - ./instance:/app/instance
    expose:           # internal only; reachable by "web:8000" from nginx
      - "8000"
    env_file:
      - ./.env
    restart: always

  nginx:
    image: nginx:latest
    container_name: shopee_nginx
    ports:
      - "127.0.0.1:80:80"   # local-only! Funnel will publish it
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/static:/var/www/static:ro
    depends_on:
      - web
