services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: shopee_web
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./logs:/app/logs
      - ./instance:/app/instance
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - LOG_LEVEL=INFO
    restart: always

  nginx:
    image: nginx:latest
    container_name: shopee_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    restart: always
